version: '3.8'

services:
  app:
    build: .
    image: alexbakker/carlease
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/carlease?createDatabaseIfNotExist=true&autoReconnect=true
      SPRING_DATASOURCE_USERNAME: execute
      SPRING_DATASOURCE_PASSWORD: order66
    ports:
      - 8091:8091
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306", "--", "java", "-jar", "/carlease.jar"]
    networks:
      - app
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carlease
      MYSQL_USER: execute
      MYSQL_PASSWORD: order66
    networks:
      - app
    security_opt:
      - seccomp:unconfined
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8092:8080
    networks:
      - app
networks:
    app: